services:
  postgres-comments:
    image: postgres:alpine
    ports:
      - "5454:5432"
    container_name: "focus_container"
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-init db.d/init.sql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
volumes:
  postgresql:
